### ISSUE TITLE
Fix argument parsing for py_mimic_fhir

### ISSUE THREAD

**Issue by alistairewj** [kind-lab/mimic-fhir#58]
I noted two potential bugs in running `python py_mimic_fhir`:

- If you do not have the MIMIC_FHIR_LOG_PATH environment variable set, and you try to use the --log_path input argument, it doesn't work (complains log_path is not provided)
- If you provide a directory which does not exist, it fails. Probably for logs we should warn/create the folder.

**Comment by alexmbennett2** [comment]
Log folder created if not present, and warns if not MIMIC_FHIR_LOG_PATH
