### ISSUE TITLE
Pathling import of mimic-fhir resources

### ISSUE THREAD

**Issue by alexmbennett2** [kind-lab/mimic-fhir#61]
For the tutorial demo of mimic-fhir, my hope was to use Pathling to demonstrate different fhir functions. But I am hitting a roadblock right off the bat, the $import is failing. The steps I have taken:
- Started pathling with docker: docker run --rm -p 8080:8080 aehrc/pathling
- Put the patient.ndjson in the /usr/share/staging folder (default for pathling)
- Created parameters and posted to pathling server using this [notebook](https://github.com/kind-lab/mimic-fhir/blob/tutorial_demo/tutorial/mimic-fhir-tutorial-pathling.ipynb)

But I am getting an error saying that there is an error reading the file. I've given all permissions to the /usr/share/staging folder so that should be fine. @jpwiedekopf you had mentioned using Pathling, any ideas?

**Comment by jpwiedekopf** [comment]
Hi, I haven't actually ever tried using Pathling myself, so I don't have any experience either. I'll investigate this next Monday, alright?

**Comment by alexmbennett2** [comment]
My bad, I thought you had used Pathling. Anyways the Pathling instructions appear clear, so give it a test Monday and see what you find. I'll post a question to Pathling if it doesn't work on your side too.

**Comment by jpwiedekopf** [comment]
[pathling.zip](https://github.com/kind-lab/mimic-fhir/files/8699117/pathling.zip)

What I was surprised by is that apparently Pathling does not ship with the nice GUI from the Pathling website, which I think is what would make Pathling such a great option for the demo. Maybe CSIRO could provide the GUI to us if we ask nicely? It looks like you are still able to point the GUI at go.pathling.app to your own server if you have an account (no idea where to get that from...), but that is probably not an option for the Demo.

**Comment by alexmbennett2** [comment]
Great! Glad you got it working. Looks like I was just specifying the local directory slightly wrong, but it works now by pointing to the directory beside the docker-compose.yml.

And ya the Pathling GUI looks nice. I've sent a message to the Pathling group inquiring about accounts and usage licensing. Let's see what they say!
