### ISSUE TITLE
mimiciv_ed.edstays referenced in fhir_patient.sql is not part of mimiciv 2.2?

### ISSUE THREAD

**Issue by sebbarb** [kind-lab/mimic-fhir#84]
Hi, when running fhir_patient.sql it doesn't find mimiciv_ed.edstays, I believe this table is not part of MIMIC-IV v2.2, or am I missing something?
The script runs fine when the related code is removed (just using adm_RACE).

**Comment by alistairewj** [comment]
It's not strictly a part of MIMIC-IV v2.2 but you can access it in a similar manner here: https://physionet.org/content/mimic-iv-ed/

The data overlaps with MIMIC-IV v2.2 so we merge the datasets together.

**Comment by sebbarb** [comment]
got it, thank you
