### ISSUE TITLE
Is complete version available for download?

### ISSUE THREAD

**Issue by JHLiu7** [kind-lab/mimic-fhir#87]
Hi there,

Thanks for the great effort here. I read from the jamia paper that `A complete version with all data in MIMIC-IV on FHIR will be available to those approved with credentialed access on PhysioNet.` Where can I find this?

**Comment by JHLiu7** [comment]
BTW, are the 100 pts in the [released demo](https://physionet.org/content/mimic-iv-fhir-demo/2.0/) equivalent to those in the [mimic-iv-demo](https://physionet.org/content/mimic-iv-demo/2.2/)? I had a quick look at `Condition` and `diagnosis_icd`, the numbers of entries don't seem to match.

**Comment by alistairewj** [comment]
It really should be! I am working on it when I can. We plan to publish the full version on PhysioNet soon.

**Comment by alistairewj** [comment]
> BTW, are the 100 pts in the [released demo](https://physionet.org/content/mimic-iv-fhir-demo/2.0/) equivalent to those in the [mimic-iv-demo](https://physionet.org/content/mimic-iv-demo/2.2/)? I had a quick look at `Condition` and `diagnosis_icd`, the numbers of entries don't seem to match.

Yes they are the same patients. Where did you find differences? Very interested to know!

**Comment by JHLiu7** [comment]
Thanks for the reply, Alistair! 

Regarding the differences, I found four pts with different codes. Here are the four from `diagnosis_icd` that don't seem to have any matches in `Condition`:

> subject (10039831)	num of codes found (7)
codes: 1962,3051,44489,9982,E8700,V1009,V1042

> subject (10039997)	num of codes found (29)
codes: 2724,27800,3051,32723,4019,4373,43889,72989,D696,D72819,E785,F17210,F17210,F309,F329,F4310,G8191,I10,I129,I480,I6340,I69354,I69354,I69392,I69893,N189,R2681,V8532,Z9181

> subject (10039708)	num of codes found (198)
codes: 2449,2651,2662,2749,2859,30391,3051,3575,4019,49390,A4189,D124,D539,D539,D539,D61818,D62,D62,D62,D631,D638,D649,D649,D649,D689,D6959,D6959,D696,D696,D696,E039,E039,E039,E039,E039,E039,E039,E039,E43,E43,E46,E5112,E5112,E59,E60,E870,E872,E872,E872,E872,E872,E873,E875,E876,F1010,F1019,F1020,F1020,F1020,F1020,F10239,F10251,F17200,F17210,F17210,F17210,F17210,F17210,F17210,F17210,G629,G9340,I10,I120,I120,I120,I129,I129,I129,I214,I340,I5021,I5181,I82401,I8510,I8510,I8510,I8511,I959,J189,J45909,J45909,J45909,J45909,J45909,J690,J95851,J9691,K284,K5730,K7010,K7010,K7010,K7011,K7030,K7030,K7030,K7030,K7031,K7031,K7040,K7040,K7290,K7290,K7460,K767,K767,K767,K7681,K8520,K859,K860,K861,K861,K921,M109,M109,M109,M109,M109,N170,N179,N179,N179,N183,N184,N186,N186,N186,N186,N186,N189,N281,R0902,R197,R2232,R300,R34,R410,R600,R600,R64,R64,R6521,R680,R740,R740,R748,R7989,S0003XA,S20221A,S20222A,S40021A,S40022A,S8011XA,S8012XA,T473X6A,T8242XA,V4586,W108XXA,Y828,Y848,Y92018,Y92230,Y929,Z66,Z681,Z6830,Z720,Z86718,Z86718,Z86718,Z86718,Z86718,Z86718,Z8711,Z91128,Z980,Z9884,Z9884,Z9884,Z9884,Z9884,Z992,Z992,Z992,Z992,Z992

> subject (10040025)	num of codes found (259)
codes: 2449,2449,25000,25000,25040,25040,2724,2724,2724,2749,2749,2749,27800,27800,27800,2859,2859,30183,30521,311,311,32723,33829,33829,34690,36230,40390,40390,40390,40390,412,412,412,412,41401,41401,41401,42731,42731,42731,4280,4280,4280,4280,42830,42832,42833,4401,4439,4473,45981,5849,5849,5853,5853,5853,5859,6820,71690,71940,B952,B954,B965,B9689,D509,D62,D62,D631,D649,D649,D649,D649,E039,E039,E039,E039,E039,E039,E1122,E1122,E1122,E1122,E1122,E1122,E1152,E1152,E11621,E11621,E11621,E11622,E11628,E11649,E11649,E278,E669,E669,E669,E669,E669,E785,E785,E785,E785,E785,E785,E860,E871,E9320,E9444,F05,F329,F329,F329,F329,F329,F329,F419,F419,G43109,G8929,H34239,I130,I130,I130,I130,I130,I130,I2510,I2510,I2510,I2510,I2510,I2510,I252,I252,I252,I252,I252,I272,I340,I4891,I4891,I4891,I4891,I4891,I4891,I5022,I5023,I5032,I5032,I5033,I509,I701,I701,I701,I70262,I7789,J441,J449,J690,J9691,K219,K5791,K5903,L03116,L03116,L89899,L97229,L97419,L97429,L97523,L97529,L97529,M109,M109,M109,M109,M109,M109,N170,N179,N179,N179,N183,N183,N183,N184,N184,N184,R159,R197,R748,R791,R791,R791,R918,S9032XA,T402X5A,T45515A,T465X5A,T501X5A,T8119XA,T8131XA,T814XXA,V0179,V1582,V1582,V1582,V4582,V4582,V4582,V4582,V5861,V5861,V5861,V5866,V5867,V5867,V5867,V8536,V8537,W208XXA,Y832,Y92230,Y92239,Y929,Y929,Z1621,Z1623,Z515,Z66,Z6830,Z6830,Z6832,Z6832,Z6833,Z781,Z7901,Z7901,Z7901,Z7902,Z7902,Z7902,Z794,Z794,Z794,Z794,Z794,Z800,Z87891,Z87891,Z87891,Z87891,Z87891,Z955,Z955,Z955,Z955,Z955



And four pts from `Condition` that I can't map to `diagnosis_icd`:
> subject (Patient/95fa0da2-f5a6-5fc9-adcf-f66e05a8cf99)	num of codes found (3)
codes: D1802,G40909,I619

> subject (Patient/ece255e8-656b-5e09-8da9-33f88bc270a1)	num of codes found (14)
codes: 25000,4019,78659,I10,I2119,I2510,I442,I9589,K219,R001,R740,V1582,V173,Z87891

> subject (Patient/87dd177c-b3f5-584e-bf76-86e2ee047c1f)	num of codes found (71)
codes: C439,C439,C7951,C799,D638,D696,E7849,E785,E785,E871,I071,I079,I10,I10,I130,I2510,I2510,I2510,I255,I255,I272,I272,I2720,I2720,I2781,I281,I4510,I4510,I480,I480,I480,I480,I5023,I5023,I5033,I509,I6523,J189,J439,J439,J449,J90,J9691,K219,K219,K219,K4030,N179,N179,N183,N183,N400,N400,N400,R740,Z7902,Z7902,Z7982,Z7982,Z8673,Z87891,Z87891,Z87891,Z87891,Z902,Z902,Z951,Z951,Z951,Z955,Z9861

> subject (Patient/b6769365-7062-53bf-850f-eddd09ebcf05)	num of codes found (80)
codes: 2749,40390,412,4148,4148,42731,42731,4280,4280,42822,42822,5859,5859,D638,D649,D649,D696,E43,E785,E785,E860,E871,E872,E875,E875,G629,G9341,I081,I130,I130,I2109,I214,I2510,I2510,I2510,I252,I252,I252,I255,I255,I255,I2720,I442,I482,I482,I4891,I5022,I5023,I5023,I5084,I7101,J9601,L270,M109,M109,M1990,N179,N179,N189,N189,N189,N400,R34,R570,R627,R627,R7989,T465X5A,V4502,V5861,Y92230,Z4502,Z66,Z66,Z681,Z781,Z7901,Z7901,Z7902,Z95810

Meanwhile, I can find the above four pts from `Condition` in the complete set of `diagnosis_icd` in mimic-iv.

**Comment by ewulczyn** [comment]
> It really should be! I am working on it when I can. We plan to publish the full version on PhysioNet soon.

Thank you for your efforts on this! Are there any updates? It would be amazing to have the full version on PhysioNet.

**Comment by alistairewj** [comment]
I have submitted the full version to PhysioNet today (very delayed of course), so hopefully it will be published in the next month. I will ask them to use the following URL: https://physionet.org/content/mimic-iv-fhir/

When it's up @JHLiu7 you might want to re-raise the issue about the mismatches. Probably, given the extensive time it took to publish it, inconsistencies between the code / published data will be lurking!

**Comment by JHLiu7** [comment]
Sounds good, thanks Alistair!

**Comment by ewulczyn** [comment]
@alistairewj thank you submitting the full version to PhysioNet! Any updates on when the data might by available?
